app: lottery-auto-script
component: multi-scf
name: scf-nodejs

# 更多内容请查看: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
inputs:
  src: ./ # 执行目录
  region: ap-guangzhou # 部署目标地区。 更多参考 https://cloud.tencent.com/document/api/583/17238#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  runtime: Nodejs12.16 # 运行环境。[Nodejs10.15, Nodejs12.16]
  memorySize: 64 # 函数运行内存，单位MB。[64, 128, ... 3072]，以 128 递增
  timeout: 900 # 函数超时时间，单位秒，范围 1-900
  functions:
    start:
      handler: main.start
    check:
      handler: main.check
    clear:
      handler: main.clear
  triggers:
    - type: timer
      function: start
      parameters:
        name: timer1
        cronExpression: "0 12 * * *" # 每天12点
        enable: true
    - type: timer
      function: check
      parameters:
        name: timer2
        cronExpression: "0 * * * *" # 每小时秒触发一次
        enable: true
    - type: timer
      function: clear
      parameters:
        name: timer3
        cronExpression: "0 0 1 */2 *" # 每六十天触发一次
        enable: true