name: 'Automatic check'
on:
  workflow_dispatch:
      branches:
      - main
  schedule:
    - cron: '0 */2 * * *'
env:
  SCKEY: ${{ secrets.SCKEY }}
  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
  PAT: ${{ secrets.PAT }}
jobs:
  lottery_1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 1
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          npm install
          npm run check
  lottery_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 2
          COOKIE: ${{ secrets.COOKIE2 }}
        run: |
          npm install
          npm run check
  lottery_3:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 3
          COOKIE: ${{ secrets.COOKIE3 }}
        run: |
          npm install
          npm run check
  lottery_4:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 4
          COOKIE: ${{ secrets.COOKIE4 }}
        run: |
          npm install
          npm run check
  lottery_5:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 5
          COOKIE: ${{ secrets.COOKIE5 }}
        run: |
          npm install
          npm run check
