name: 'Automatic clear dynamic&follow'
on:
  workflow_dispatch:
      branches:
      - main
  schedule:
    - cron: '0 0 */15 * *'
jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          COOKIE_1: ${{ secrets.COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run:
          npm run clear