name: "Build and push Docker images"

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "*.js"
      - "*.json"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repo: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          curl -fsSL https://get.docker.com | bash -s docker
          docker build -t $repo .
          docker login -p $password -u $username
          docker push $repo
