name: Node.js CI
on:
  push:
    branches: 
      - main
      - master
  schedule:
    - cron: '51 0-23 * * *'
jobs:
  Start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Nodejs run'
        shell: bash
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run:
          node main.js COOKIE=$COOKIE
