name: "Package Node.js project into an executable"
on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "main.js"
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "main.js"
  workflow_dispatch:
    branches:
      - main
jobs:
  pkg_x64:
    runs-on: windows-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: "Pkg this"
        run: |
          npm install
          npm run pkg_x64
      - name: "Upload to artifact"
        uses: actions/upload-artifact@v2
        with:
          name: dist_x64
          path: dist/
  pkg_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: "Pkg this"
        run: |
          npm install
          npm run pkg_arm64
      - name: "Upload to artifact"
        uses: actions/upload-artifact@v2
        with:
          name: nlts-linux-arm64
          path: dist/
  pkg_armv7:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: "Pkg this"
        run: |
          npm install
          npm run pkg_armv7
      - name: "Upload to artifact"
        uses: actions/upload-artifact@v2
        with:
          name: nlts-linux-armv7
          path: dist/
